# Stage 1: Build the application
FROM maven:3.8.4-openjdk-17 AS build

# Set build-time arguments
ARG DB_URL
ARG DB_USER
ARG DB_PASSWORD
ARG AWS_S3_ACCESS_KEY
ARG AWS_S3_SECRET_KEY
ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIS_USERNAME
ARG REDIS_PASSWORD
ARG REDIS_CONNECTION_STRING
ARG TZ
ARG MAIL_USERNAME
ARG MAIL_PASSWORD
ARG FB_TYPE
ARG FB_PROJECT_ID
ARG FB_PRIVATE_KEY_ID
ARG FB_PRIVATE_KEY
ARG FB_CLIENT_EMAIL
ARG FB_CLIENT_ID
ARG FB_AUTH_URI
ARG FB_TOKEN_URI
ARG FB_AUTH_PROVIDER_X509_CERT_URL
ARG FB_CLIENT_X509_CERT_URL
ARG FB_UNIVERSE_DOMAIN

# Pass build-time arguments as environment variables
ENV DB_URL=${DB_URL}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
ENV AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_USERNAME=${REDIS_USERNAME}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
ENV TZ=${TZ}
ENV MAIL_USERNAME=${MAIL_USERNAME}
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV FB_TYPE=${FB_TYPE}
ENV FB_PROJECT_ID=${FB_PROJECT_ID}
ENV FB_PRIVATE_KEY_ID=${FB_PRIVATE_KEY_ID}
ENV FB_PRIVATE_KEY=${FB_PRIVATE_KEY}
ENV FB_CLIENT_EMAIL=${FB_CLIENT_EMAIL}
ENV FB_CLIENT_ID=${FB_CLIENT_ID}
ENV FB_AUTH_URI=${FB_AUTH_URI}
ENV FB_TOKEN_URI=${FB_TOKEN_URI}
ENV FB_AUTH_PROVIDER_X509_CERT_URL=${FB_AUTH_PROVIDER_X509_CERT_URL}
ENV FB_CLIENT_X509_CERT_URL=${FB_CLIENT_X509_CERT_URL}
ENV FB_UNIVERSE_DOMAIN=${FB_UNIVERSE_DOMAIN}

WORKDIR /app
COPY pom.xml .
COPY src ./src
COPY firebase-config.json /app/firebase-config.json  # Copy your firebase-config.json file

RUN mvn clean install

# Stage 2: Run the application
FROM openjdk:17-jdk-slim

# Set environment variables for runtime
ENV DB_URL=${DB_URL}
ENV DB_USER=${DB_USER}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV AWS_S3_ACCESS_KEY=${AWS_S3_ACCESS_KEY}
ENV AWS_S3_SECRET_KEY=${AWS_S3_SECRET_KEY}
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}
ENV REDIS_USERNAME=${REDIS_USERNAME}
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ENV REDIS_CONNECTION_STRING=${REDIS_CONNECTION_STRING}
ENV TZ=${TZ}
ENV MAIL_USERNAME=${MAIL_USERNAME}
ENV MAIL_PASSWORD=${MAIL_PASSWORD}
ENV FB_TYPE=${FB_TYPE}
ENV FB_PROJECT_ID=${FB_PROJECT_ID}
ENV FB_PRIVATE_KEY_ID=${FB_PRIVATE_KEY_ID}
ENV FB_PRIVATE_KEY=${FB_PRIVATE_KEY}
ENV FB_CLIENT_EMAIL=${FB_CLIENT_EMAIL}
ENV FB_CLIENT_ID=${FB_CLIENT_ID}
ENV FB_AUTH_URI=${FB_AUTH_URI}
ENV FB_TOKEN_URI=${FB_TOKEN_URI}
ENV FB_AUTH_PROVIDER_X509_CERT_URL=${FB_AUTH_PROVIDER_X509_CERT_URL}
ENV FB_CLIENT_X509_CERT_URL=${FB_CLIENT_X509_CERT_URL}
ENV FB_UNIVERSE_DOMAIN=${FB_UNIVERSE_DOMAIN}

WORKDIR /app
COPY --from=build /app/target/backend.jar /app/backend.jar
COPY --from=build /app/firebase-config.json /app/firebase-config.json  # Copy firebase-config.json again in the runtime stage
EXPOSE 8086
CMD ["java", "-jar", "/app/backend.jar"]
